# Generated by Django 5.2.6 on 2025-09-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('conejo', 'Conejo'), ('ave', 'Ave'), ('hamster', 'Hámster'), ('Pez', 'Pez'), ('Tortuga', 'Tortuga'), ('otro', 'Otro')], max_length=10),
        ),
    ]
