# Generated by Django 5.2.6 on 2025-09-21 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_mascotas', '0002_alter_mascota_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(help_text='Nombre de la mascota', max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='SolicitudPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('conejo', 'Conejo'), ('ave', 'Ave'), ('hamster', 'Hámster'), ('Pez', 'Pez'), ('Tortuga', 'Tortuga'), ('otro', 'Otro')], max_length=10)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(help_text='Edad en meses')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/solicitudes/')),
                ('estado', models.CharField(default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publicacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
