# Generated by Django 5.2.6 on 2025-09-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_mascotas', '0003_alter_mascota_nombre_alter_mascota_raza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='acepta_declaracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='contacto_direccion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='contacto_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='contacto_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='contacto_telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
