# Generated by Django 5.2.6 on 2025-09-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_mascotas', '0004_solicitudpublicacion_acepta_declaracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='aceptacion_mensaje',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='rechazo_motivo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
